### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by military1** [santrancisco/relaysecret#1]
Hello!
Very interesting. I would be grateful if you could describe how to install it on a server for less experienced users.

**Comment by santrancisco** [comment]
Thank you for reaching out. I have yet had any plan to convert it into a python flask project or the like to run in standalone server/EC2. 

With that said, the aim for this project is to minimise any attack surface and thus having the only dynamic code running in an isolated lambda function and offload the handle of HTTP requests to Amazon API gateway is, in my opinion, much safer.

To deploy the project in your own AWS environment, it is very easy using the latest version of terraform. Once you install terraform and sign up for a free trial account with AWS, go into relaysecret/backend/terraform/, rename terraform.tfvars.example to terraform.tfvars and modify the variables with your own deploymentname, the AWS account id. 

The VirusTotal API key (VTAPIKEY) is optional, you can leave it as none if you dont have one. The app shares the SHA1 hash of the decrypted blob to Virustotal to check for virus, thus if you want this functionality, I would highly recommend to signup for a free API key. :)

Once you set that up, install aws cli , set up an AWS Access&Secret key and just run `terraform apply` to deploy the stack. Tearing everything down is as simple as running `terraform destroy`.

Hope that helps!

**Comment by okyanusoz** [comment]
If you really want to host on your own servers, you can use MinIO (https://min.io)

**Comment by santrancisco** [comment]
Closing this issue... I added [deploy your own](https://github.com/santrancisco/relaysecret#deploy-your-own) section and as mentioned above, this project is built for simplicity sake and utilise AWS S3 bucket functionality heavily to cut down necessary backend code (File upload, signed url, File expiration, scalable , etc... ), reduce attack surface tremendously by standing on giant's shoulder. 😃
