### ISSUE TITLE
recommendation: URL optimization

### ISSUE THREAD

**Issue by jackyliu16** [santrancisco/relaysecret#7]
it seems the website you have made is face to a situation that people could using link to secretly sharing file and message,
but the problem is, you still need to sharing this URL isn't it ? And the URL which auto created is a little bit longer.
so, why not provide a new function, for example. let people could using a kind of short URL, or just customize the entered room number and password to make it ?

**Comment by santrancisco** [comment]
Aha - Thanks for asking, I do have a "tunnel" or "room" mode but it is not well-known and not very polished: https://relaysecret.com/tunnel

The way it works is explained [here](https://github.com/santrancisco/relaysecret#room-mode). I hope that helps ;)

**Comment by jackyliu16** [comment]
ooo, i haven' seem this pattern, i thought it was explaining the connection between home name and passwd in url  

I was guessing that the url just like sth${random home name}#${home-passwd as hash}
